services:
  flow1:
    image: backend
    ports:
      - 1111:3000
    env_file:
      - .env
    command: ["npm", "run", "start"]
  flow2:
    image: backend
    ports:
      - 2222:3000
    env_file:
      - .env
    command: ["npm", "run", "start"]
  flow3:
    image: backend
    ports:
      - 3333:3000
    env_file:
      - .env
    command: ["npm", "run", "start"]
